### ISSUE TITLE
No neuron.dhall found in latest Docker update

### ISSUE THREAD

**Issue by crosbyhayton** [srid/neuron#401]
Hello,

I've been using and very much enjoying the Neuron Docker container that you have put together! I've had a working setup for several weeks now. I just updated my container, and the site is now failing to generate. All of my Markdown files are in the same location in the /zettelkasten directory as before I ran the update. When I check my docker logs, I see this:

```[Rib] Serving /.neuron/output at http://0.0.0.0:8080
[Rib] Generating / (rebuildAll=True)
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:

at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.19.1-1FdWp2zMJy65OeP1Lz81bk:Development.Shake.Forward
* Raised the exception:
[Rib] Watching / for changes
user error (not a neuron notes directory (no neuron.dhall found under /))
```

It seems to me that the container is looking in / instead of /zettelkasten for the neuron.dhall file (which still does exist in the /zettelkasten directory). Did I make an error in my configuration somehow?

**Comment by srid** [comment]
Neuron now defaults to current directory. https://github.com/srid/neuron/commit/5f966a571d9eb0b986031082c40b35152af4f9d6

Looks like we have to change the docker image to use /zettelkasten (or whever it is mounted) as the current directory. Meanwhile, you can pass `-d <yourvolume>` or cd to it before running neuron. 

Oh, and you will need a neuron.dhall: `touch neuron.dhall` will do it.

**Comment by crosbyhayton** [comment]
Okay, I ran the container and added `-d /zettelkasten` to my startup command, and it is now properly recognizing my neuron.dhall file, however the container now seems to get upset at the "-ws 0.0.0.0:8080" command that was working previously per the [Docker workflow page here](https://neuron.zettel.page/c6176636.html), and now throws:
```
Invalid option `-ws'
```
into logs after the container is created. I tried changing the 's' to 'S' to match the [Tutorial](https://neuron.zettel.page/tutorial.html), but neither of those seem to work now. Did the commands for serving Neuron change as well?

**Comment by srid** [comment]
Fixed, and a new docker image pushed. Try the new CLI at https://neuron.zettel.page/docker.html

**Comment by crosbyhayton** [comment]
Excellent, thank you! I pulled a new image, updated my directory of .md to mount into /notes in the new container, and I'm fully back in business!

**Comment by Ronnie76er** [comment]
Wow what timing, I was literally just trying this. I think you want to remove the `:dev` from the image name in the documentation, so just: `sridca/neuron`.

**Comment by furkhat** [comment]
Error is still present.
`no neuron.dhall found under /notes`:
```
➜  zettelkasten docker run --rm -t -i -p 8080:8080 -v $(pwd):/notes sridca/neuron:latest neuron rib -ws 0.0.0.0:8080
[Rib] Serving /notes/.neuron/output at http://0.0.0.0:8080
[Rib] Generating /notes (rebuildAll=True)
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:
  at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.19.1-Jffais3OOiA8eQQKIWz97P:Development.Shake.Forward
* Raised the exception:
user error (not a neuron notes directory (no neuron.dhall found under /notes))

[Rib] Watching /notes for changes
```

Image version (the latest on docker hub) - `Digest: sha256:db3b16b7898161bf341f9ed26418510ad91fcb9b850305c1fd4bcce576da7755`
```
docker pull sridca/neuron:latest
latest: Pulling from sridca/neuron
Digest: sha256:db3b16b7898161bf341f9ed26418510ad91fcb9b850305c1fd4bcce576da7755
Status: Image is up to date for sridca/neuron:latest
docker.io/sridca/neuron:latest
```

**Comment by srid** [comment]
Can't reproduce:

![image](https://user-images.githubusercontent.com/3998/96347141-94de2c00-106d-11eb-84b2-768a34378bd2.png)

Did you a create a `neuron.dhall` in your current directory? It can be an empty file.

**Comment by srid** [comment]
@furkhat Fixed docs in https://github.com/srid/neuron/commit/e595b7df6ec784451bab38c0d4c0e871de5b1c4f
